version: '2'
services:
  web:
    build: .
    ports:
     - "3333:3333"
    command: bash -c 'npm run build && npm run start'
    environment:
      NODE_ENV: 'production'
    volumes:
     - ./:/usr/src/app
